### ISSUE TITLE
Switch task queue to Odoo-celery

### ISSUE THREAD

**Issue by jeremi** [newlogic/newlogic-g2p#1]
- [ ] migrate Odoo celery to Odoo 15.0 https://github.com/novacode-nl/odoo-celery
- [ ] move the ODK import to odoo-celery

**Comment by jeremi** [comment]
Can you first let me know how much work you think it is to migrate it?

**Comment by gonzalesedwin1123** [comment]
I started working on this. I will update you regarding the assistance I need for Celery and the estimates in time required to migrate this to Odoo15.
