### ISSUE TITLE
When creating a program using the wizard, add a step to import registrant that match the criteria

### ISSUE THREAD

**Issue by jeremi** [newlogic/newlogic-g2p#16]

**Comment by jeremi** [comment]
- We should as `individual` or `group` in the first step instead of the second/
- Change `Would you like to generate beneficiaries?` -> `Would you like to import the matching registrants to this program?`

Also when I tried, I got stuck with this error (It did not happen if I did not import the registrants):
![Image](https://user-images.githubusercontent.com/9537/179617101-5384ac9d-19c6-48df-b293-d4a9d2e477f9.png)

**Comment by gonzalesedwin1123** [comment]
Errors are fixed in the latest commit
